apiVersion: v1
kind: Namespace
metadata:
  name: svc-acc-test-ns


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-svc-acc
  namespace: svc-acc-test-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: svc-acc-test-ns
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-rolebinding
  namespace: svc-acc-test-ns
subjects:
  - kind: ServiceAccount
    name: test-svc-acc
    namespace: svc-acc-test-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader

